# Generated by Django 5.1.7 on 2025-04-06 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0001_initial'),
        ('rbc', '0011_remove_orders_item_orders_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In Queue', 'Queue'), ('Preparing!', 'Making'), ('Prepared.', 'Completed'), ('Out For Delevery', 'Out'), ('Delivered', 'Done'), ('Canceled', 'Canceled')], default='In Queue', max_length=17)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemCart.cartses')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemCart.cartitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbc.user_details')),
            ],
        ),
    ]
