# Generated by Django 5.1.7 on 2025-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0002_order1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='items',
        ),
        migrations.AddField(
            model_name='order1',
            name='items',
            field=models.ManyToManyField(to='itemCart.cartitems'),
        ),
    ]
