# Generated by Django 5.1.7 on 2025-04-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0003_remove_order1_items_order1_items'),
        ('rbc', '0011_remove_orders_item_orders_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemCart.cartses')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbc.food')),
            ],
        ),
        migrations.AlterField(
            model_name='order1',
            name='items',
            field=models.ManyToManyField(to='itemCart.ordereditems'),
        ),
    ]
