# Generated by Django 5.1.7 on 2025-04-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0004_ordereditems_alter_order1_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='items',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='cart',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itemCart.order1'),
        ),
    ]
