# Generated by Django 6.0 on 2026-01-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCart', '0005_remove_order1_items_remove_ordereditems_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
    ]
