# Generated by Django 5.1.7 on 2025-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0003_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='course',
            field=models.CharField(blank=True, choices=[('Appetizer', 'Appe'), ('Hot Hot Soup', 'Soup'), ('Indian Starter', 'Starter'), ('Salad, Papad And Raita', 'Salad'), ('Breads', 'Bread'), ('Chinese', 'Chi')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(blank=True, choices=[('NON-VEG', 'Nv'), ('VEG', 'V')], max_length=7, null=True),
        ),
    ]
