# Generated by Django 5.1.7 on 2025-04-05 07:00

import django.db.models.deletion
import django.utils.timezone
import rbc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0004_food_course_food_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(blank=True, choices=[('Appetizer', 'Appe'), ('Hot Hot Soup', 'Soup'), ('Indian Starter', 'Starter'), ('Salad, Papad And Raita', 'Salad'), ('Rice', 'Rice'), ('Breads', 'Bread'), ('Chinese', 'Chi'), ('Tandoor', 'Tand'), ('Main Course Veg', 'Main Veg'), ('Main Course Non-Veg', 'Main Nv'), ('Desert', 'Desert')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('rating', models.BooleanField(default='Great', verbose_name=rbc.models.Review.Rating)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbc.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
