# Generated by Django 5.1.7 on 2025-04-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0005_food_created_food_updated_alter_food_course_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ManyToManyField(to='rbc.rating'),
        ),
    ]
