# Generated by Django 5.1.7 on 2025-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0006_rating_remove_review_rating_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Ok'), (3, 'Average'), (4, 'Good'), (5, 'Great')], default=3),
            preserve_default=False,
        ),
    ]
