# Generated by Django 5.1.7 on 2025-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0007_remove_review_rating_delete_rating_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.BooleanField(choices=[(1, 'Poor'), (2, 'Ok'), (3, 'Average'), (4, 'Good'), (5, 'Great')]),
        ),
    ]
