# Generated by Django 5.1.7 on 2025-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Ok'), (3, 'Average'), (4, 'Good'), (5, 'Great')]),
        ),
    ]
