# Generated by Django 5.1.7 on 2025-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbc', '0010_user_details_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ManyToManyField(to='rbc.food'),
        ),
    ]
